---

- hosts: fortigates
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 9443
  tasks:
  - name: Configure data_vlan
    fortios_system_interface:
      vdom: "{{ vdom }}"
      state: "present"
      system_interface:
        interface: "sw1"
        type: "vlan"
        vlanid: "10"
        mode: "static"
        ip: "10.10.1.1 255.255.255.0"
        allowaccess: ['https', 'ping']
        name: "sw1.0010"
        alias: "data_vlan"
        vdom: "root"